<?php

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/**
 * @var Escaper $escaper
 * @var Template $block
 */
?>
<div class="meteomatics-weather" data-bind="scope: 'weather'">
    <h3><?= $escaper->escapeHtml('Weather') ?></h3>
    <div class="properties">
        <div><?= $escaper->escapeHtml('Temperature: ') ?></div>
        <div data-bind="text: weather().temperature"></div>
        <div><?= $escaper->escapeHtml('Precipitation: ') ?></div>
        <div data-bind="text: weather().precipitation"></div>
        <div><?= $escaper->escapeHtml('Wind Speed: ') ?></div>
        <div data-bind="text: weather().wind_speed"></div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".meteomatics-weather": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "weather": {
                        "component": "Meteomatics_Weather/js/weather"
                    }
                }
            }
        }
    }
</script>
